### Get All
GET http://localhost:3000/products

### Get One
GET http://localhost:3000/products/1

### Create One
POST http://localhost:3000/products
Content-Type: application/json

{
    "price": 20,
    "name": "Carteira da Fendi"
}


### Update one
PATCH  http://localhost:3000/products/1
Content-Type: application/json

{
    "price": 20,
    "name": "Carteira da Tommy"
}

### Delete One
DELETE  http://localhost:3000/products/3
