### Get All
GET http://localhost:3000/products

### Get One
GET http://localhost:3000/products/5

### Create One
POST http://localhost:3000/products
Content-Type: application/json

{
    "price": 20,
    "name": "Carteira da Fendi"
}


### Update one
PATCH  http://localhost:3000/products/3
Content-Type: application/json

{
    "price": 20,
    "name": "Carteira da Tommy"
}

### Delete One
DELETE  http://localhost:3000/products/3



## Stock Input
###
POST http://localhost:3000/stock-input
Content-Type: application/json

{
    "productID": 5,
    "quantity": 5,
    "date": "2023-11-29"
}

### Get All
GET http://localhost:3000/stock-input

### Get One
GET http://localhost:3000/stock-input/22


## Stock Output
###
POST http://localhost:3000/stock-output
Content-Type: application/json

{
    "productID": 5,
    "quantity": 5,
    "date": "2023-11-29"
}

### Get All
GET http://localhost:3000/stock-output

### Get One
GET http://localhost:3000/stock-output/22